import Anthropic from '@anthropic-ai/sdk';
import { ScheduleData, ScheduleSolution, Appointment, WishRequest, WishSolution, FixItOptions } from './types';
import { v4 as uuidv4 } from 'uuid';
import {
  buildAnonymizationMap,
  anonymizeAppointment,
  anonymizeSchedule,
  scrubText,
  deAnonymizeText,
  AnonymizationMap,
} from './anonymizer';
import { summarizeWish } from './wish';
import { parseWishSolutions } from './wish';
import { allowedStrategies } from './fixit';
import { computeClientCompliance, computeTechCompliance, monthPeriod } from './compliance';
import { resolveUtilization } from './utilization';
import { buildFillContext, buildComplianceFillContext, buildSupervisableWindows, buildFeasibilityDiagnostics } from './fillSchedule';
import { startOfWeek } from 'date-fns';

export type ClaudeModel = 'claude-opus-4-8' | 'claude-sonnet-4-6' | 'claude-haiku-4-5-20251001';

export const DEFAULT_MODEL: ClaudeModel = 'claude-sonnet-4-6';

export class ClaudeScheduler {
  private client: Anthropic;
  private data: ScheduleData;
  private model: ClaudeModel;
  private anonMap: AnonymizationMap;

  constructor(apiKey: string, data: ScheduleData, model: ClaudeModel = DEFAULT_MODEL) {
    // The native iOS WebView has no server, so solutions are generated by
    // calling Anthropic directly from the client. The key is the user's own and
    // never leaves the device except in this request; the anonymizer guarantees
    // no client/tech names are included in the prompt (see generateSolutions).
    this.client = new Anthropic({ apiKey, dangerouslyAllowBrowser: true });
    this.data = data;
    this.model = model;
    // Build anonymization map once per request - tokens stay consistent within a single Claude call.
    this.anonMap = buildAnonymizationMap(data);
  }

  async generateSolutions(
    changedAppointment: Appointment,
    currentConflicts: string[]
  ): Promise<ScheduleSolution[]> {
    const prompt = this.buildPrompt(changedAppointment, currentConflicts);

    // SAFETY ASSERTION: prompt should not contain any client/tech original names.
    // If it does, the anonymizer has a bug — don't send the request.
    if (this.containsRawNames(prompt)) {
      throw new Error('Anonymization check failed: prompt would leak PII. Aborting Claude call.');
    }

    const response = await this.client.messages.create({
      model: this.model,
      max_tokens: 2000,
      messages: [
        {
          role: 'user',
          content: prompt,
        },
      ],
    });

    const content = response.content[0];
    if (!content || content.type !== 'text') {
      return [];
    }

    // De-anonymize tokens in the reply before parsing structured fields.
    const deanon = deAnonymizeText(content.text, this.anonMap);
    return this.parseSolutions(deanon, changedAppointment);
  }

  // "Wish It": a goal-driven rework. Returns up to 3 WishSolutions whose ops
  // (move/add/remove/blackout) the caller stages into the draft or applies.
  async generateWishSolutions(wish: WishRequest): Promise<WishSolution[]> {
    const prompt = this.buildWishPrompt(wish);
    if (this.containsRawNames(prompt)) {
      throw new Error('Anonymization check failed: prompt would leak PII. Aborting Claude call.');
    }
    const response = await this.client.messages.create({
      model: this.model,
      max_tokens: 3000,
      messages: [{ role: 'user', content: prompt }],
    });
    const content = response.content[0];
    if (!content || content.type !== 'text') return [];
    // Parse tokens out of the JSON via the reverse map (don't string-replace the
    // whole reply — that would corrupt ISO timestamps that contain digits).
    return parseWishSolutions(content.text, token => this.anonMap.reverse.get(token));
  }

  // "Fix It": compliance remediation. Hands the model the under-target cases and
  // techs plus the BCBA's chosen strategies, and asks for up to 3 compliant ways
  // to close the gaps. Output reuses the WishSolution op shape.
  async generateFixSolutions(options: FixItOptions, conflicts: string[]): Promise<WishSolution[]> {
    const prompt = this.buildFixItPrompt(options, conflicts);
    if (this.containsRawNames(prompt)) {
      throw new Error('Anonymization check failed: prompt would leak PII. Aborting Claude call.');
    }
    const response = await this.client.messages.create({
      model: this.model,
      max_tokens: 3000,
      messages: [{ role: 'user', content: prompt }],
    });
    const content = response.content[0];
    if (!content || content.type !== 'text') return [];
    return parseWishSolutions(content.text, token => this.anonMap.reverse.get(token));
  }

  buildFixItPrompt(options: FixItOptions, conflicts: string[]): string {
    const now = new Date();
    const horizonWeeks = options.horizonWeeks && options.horizonWeeks > 0 ? options.horizonWeeks : 4;
    const horizonEnd = new Date(now.getTime() + horizonWeeks * 7 * 86400000);
    const period = monthPeriod(now);
    const anon = anonymizeSchedule(this.data, this.anonMap);
    const s = this.data.settings;
    const u = resolveUtilization(s.utilization);

    const excluded = new Set(options.excludedClientIds);
    const clientGaps = computeClientCompliance(this.data, period)
      .filter(r => !excluded.has(r.client.id))
      .filter(r => r.projected.hoursToGo > 0 || r.actual.hoursToGo > 0)
      .sort((a, b) => b.projected.hoursToGo - a.projected.hoursToGo) // most behind first
      .map(r => {
        const token = this.anonMap.clients.get(r.client.id) || this.anonMap.clients.get(r.client.name) || 'CLIENT_?';
        const pct = r.projected.directHours > 0
          ? (r.projected.supervisionHours / r.projected.directHours * 100).toFixed(0)
          : '0';
        return `${token}: direct ${r.actual.directHours.toFixed(1)}h, supervision ${r.actual.supervisionHours.toFixed(1)}h (${pct}%), needs ~${r.projected.hoursToGo.toFixed(1)}h more to reach target`;
      });

    const techGaps = computeTechCompliance(this.data, period)
      .filter(r => r.projected.companyHoursToGo > 0 || (r.projected.bacbHoursToGo ?? 0) > 0)
      .map(r => {
        const token = this.anonMap.technicians.get(r.tech.id) || this.anonMap.technicians.get(r.tech.name) || 'TECH_?';
        const bacb = r.projected.bacbHoursToGo ? `, BACB to-go ${r.projected.bacbHoursToGo.toFixed(1)}h` : '';
        return `${token}: direct ${r.actual.directHours.toFixed(1)}h, supv ${r.actual.supervisionHours.toFixed(1)}h, company to-go ${r.projected.companyHoursToGo.toFixed(1)}h${bacb}`;
      });

    // Compact appointment payload: only fields the model needs.
    const inScope = anon.appointments
      .filter((a: any) => {
        const t = new Date(a.startTime).getTime();
        return t >= now.getTime() && t <= horizonEnd.getTime();
      })
      .map((a: any) => ({
        id: a.id, tech: a.technician, client: a.client,
        start: a.startTime, end: a.endTime, type: a.type,
        fixed: a.isFixed || undefined,
        recur: a.isRecurring ? (a.recurringPattern || true) : undefined,
      }));

    // Precomputed supervisable windows: direct sessions where the BCBA is
    // available and not already double-booked. Giving the model these concrete
    // slots is much more reliable than asking it to derive them from raw JSON.
    const supWindows = buildSupervisableWindows(this.data, now, horizonEnd);
    const tok = (m: Map<string, string>, id: string, name: string) => m.get(id) || m.get(name) || name;
    const aptTok = (id: string) => this.anonMap.appointments.get(id) || id;
    const supWindowLines = supWindows.map(w => {
      const ct = tok(this.anonMap.clients, w.clientId, w.clientName);
      const tt = w.techName ? ` [BT:${tok(this.anonMap.technicians, w.techId || '', w.techName)}]` : '';
      return `${ct} ${aptTok(w.appointmentId)} ${w.date} ${w.sessionStart.slice(11, 16)}–${w.sessionEnd.slice(11, 16)}${tt}`;
    });

    // Feasibility diagnostics: per-client explanation of why BCBA can't supervise
    // (only include clients with gaps that have no free windows)
    const diagnostics = buildFeasibilityDiagnostics(this.data, now, horizonEnd);
    const blockedDiagLines = diagnostics
      .filter(d => d.blocker !== null && d.futureDirects > 0)
      .map(d => {
        const ct = tok(this.anonMap.clients, d.clientId, d.clientName);
        return `${ct}: ${d.blocker}`;
      });

    const strategies = allowedStrategies(options);
    const scrubbedConflicts = conflicts.map(c => scrubText(c, this.data, this.anonMap));
    const billableMin = u.bcbaWeeklyBillableMin ?? u.bcbaWeeklyBillableHours;

    const priorityLines = [
      options.prioritizeBtSupervision ? 'PRIORITY: Prefer adding BT supervision (named-BT direct + supervision overlap).' : '',
      options.prioritizeParentTraining ? 'PRIORITY: Prefer adding parent-training sessions.' : '',
    ].filter(Boolean);

    return `You are an ABA compliance assistant. Fix supervision gaps for the BCBA. All people are opaque tokens — use exact tokens, never invent names.

NOW: ${now.toISOString()}
HORIZON: ${horizonEnd.toISOString().slice(0, 10)}

FITNESS FUNCTION: Maximize (1) cases reaching the target supervision %, (2) techs hitting BACB 5% + company target, (3) BCBA billable ≈ ${billableMin ?? 'goal'}h/week. A 15-20% overage is acceptable as a cancellation buffer — DO NOT refuse to add sessions solely because they push billable slightly over the weekly goal.

GAPS TO CLOSE (sorted most behind first):
Case supervision (target ${s.supervisionDirectHoursPercent}% of direct hours):
${clientGaps.length ? clientGaps.map(g => `  ${g}`).join('\n') : '  (none — all cases at target)'}
Tech supervision (company ${s.supervisionRBTHoursPercent}%; RBTs also need BACB ≥5%):
${techGaps.length ? techGaps.map(g => `  ${g}`).join('\n') : '  (none)'}
${scrubbedConflicts.length ? `\nEXISTING WARNINGS:\n${scrubbedConflicts.map(c => `  ${c}`).join('\n')}` : ''}

SUPERVISABLE WINDOWS — direct sessions where BCBA is available and not yet booked (add supervision here):
${supWindowLines.length ? supWindowLines.join('\n') : '  (none in horizon — see BLOCKERS below)'}
${blockedDiagLines.length ? `\nBLOCKERS (why BCBA cannot supervise these clients):\n${blockedDiagLines.map(l => `  ${l}`).join('\n')}` : ''}

ALLOWED STRATEGIES: ${strategies.length ? strategies.join(', ') : '(none selected — return one solution with empty ops explaining why)'}
${priorityLines.length ? '\n' + priorityLines.join('\n') : ''}

HARD RULES — verify every op against ALL before outputting:
1. Never touch any appointment whose start < NOW.
2. Never double-book a person. The BCBA is the implicit actor on EVERY supervision/parent-training/case-planning/reassessment item — new or already in SCHEDULE. No two such items may overlap in time. Diff new ops against (a) other ops in this solution and (b) every existing supervision/PT/case-planning/reassessment row.
3. BCBA BILLABLE (soft target): Aim for ~${billableMin ?? 'goal'}h/week. Solutions MAY exceed this when needed to meet compliance — flag the overage in reasoning so the BCBA can decide what to trim. Do not voluntarily go below target without a clinical reason.
4. MAXIMIZE compliance gaps aggressively. Add as many compliant sessions as needed across the horizon — the BCBA will manually trim overages. Prefer the SUPERVISABLE WINDOWS above; only look outside them if needed.
5. "add" ops must NOT include an "id" field — the app assigns IDs.
6. "add" recurring: output only the first occurrence; the app expands the series.
7. Each of the 3 solutions must be genuinely distinct (different clients prioritized, different weeks, different session types, or different slot distributions).

SCHEDULE IN HORIZON (compact JSON):
${JSON.stringify(inScope)}

CLIENTS: ${JSON.stringify(anon.clients)}
TECHNICIANS: ${JSON.stringify(anon.technicians)}
${anon.blackouts.length ? `BLACKOUT DAYS (each entry blocks only the named entity): ${JSON.stringify(anon.blackouts)}` : ''}
${anon.timeOff.length ? `BCBA TIME OFF: ${JSON.stringify(anon.timeOff)}` : ''}

VALIDATION (do mentally before answering): For every op verify — (a) start ≥ NOW; (b) no double-book; (b2) no two BCBA items overlap; (c) tokens exist in CLIENTS/TECHNICIANS; (d) apt tokens exist in SCHEDULE; (e) entity not in BLACKOUT; (f) BCBA not in TIME OFF; (g) ignore malformed tokens like "CLIENT_nIENT_m".

OUTPUT: Strict JSON only — no prose, no markdown. Schema:
{"solutions":[{"summary":"short title","reasoning":"1-2 sentences","ops":[
  {"op":"add","title":"...","type":"supervision|parent-training|case-planning|client-session","client":"CLIENT_n or null","tech":"TECH_n or null","start":"YYYY-MM-DDTHH:mm:ss","end":"YYYY-MM-DDTHH:mm:ss","recurring":false,"pattern":null},
  {"op":"move","apt":"APT_n","start":"YYYY-MM-DDTHH:mm:ss","end":"YYYY-MM-DDTHH:mm:ss"},
  {"op":"remove","apt":"APT_n"}
]}]}
ISO times are local (no timezone suffix).

NO-SOLUTION RULE: If no compliant option exists within ALLOWED STRATEGIES, return EXACTLY ONE solution with empty ops [] and a detailed "reasoning" that for EACH case in GAPS TO CLOSE specifies: (1) does it have supervisable windows? (2) is the BCBA available during those windows? (3) would a new supervision session create a double-book? (4) is the case already at or above target? Format as "CLIENT_n: [specific reason]" per case so the BCBA knows exactly what to fix.`;
  }

  buildWishPrompt(wish: WishRequest): string {
    const now = new Date();
    // fillSchedule scopes to the compliance month; all other wishes use horizonWeeks.
    const period = monthPeriod(now);
    const horizonEnd = wish.kind === 'fillSchedule'
      ? period.end
      : new Date(now.getTime() + (wish.horizonWeeks && wish.horizonWeeks > 0 ? wish.horizonWeeks : 8) * 7 * 86400000);
    const anon = anonymizeSchedule(this.data, this.anonMap);
    const s = this.data.settings;

    // Compact payload: only fields the model needs, same as Fix It.
    const inScope = anon.appointments
      .filter((a: any) => {
        const t = new Date(a.startTime).getTime();
        return t >= now.getTime() && t <= horizonEnd.getTime();
      })
      .map((a: any) => ({
        id: a.id, tech: a.technician || undefined, client: a.client || undefined,
        start: a.startTime, end: a.endTime, type: a.type,
        fixed: a.isFixed || undefined,
        recur: a.isRecurring ? (a.recurringPattern || true) : undefined,
      }));

    const clinicianAvail = s.clinicianAvailability
      ? Object.entries(s.clinicianAvailability).map(([d, ws]) => `${d}: ${(ws as any[]).map(w => `${w.start}-${w.end}`).join(', ')}`).join('; ')
      : 'not specified';

    // Inject local solver context depending on the wish kind.
    let fillBlock = '';

    if (wish.kind === 'maximizeDirectHours') {
      // Maximize BT direct-service utilization: compute per-case gaps + feasible
      // windows for this week, then let the model assemble 3 variants.
      const weekStart = startOfWeek(now, { weekStartsOn: 1 });
      const ctx = buildFillContext(this.data, weekStart);
      const tok = (m: Map<string, string>, id: string, name: string) => m.get(id) || m.get(name) || name;
      const cases = ctx.underserved.map(u =>
        `${tok(this.anonMap.clients, u.clientId, u.clientName)}: target ${u.targetDirectHrs}h, scheduled ${u.scheduledDirectHrs}h, gap ${u.gapHrs}h`);
      const windows = ctx.windows.map(w =>
        `${tok(this.anonMap.clients, w.clientId, w.clientName)} ${w.date}(${w.day.slice(0, 3)}) ${w.start}-${w.end} [${w.techs.map(t => tok(this.anonMap.technicians, t.id, t.name)).join(',')}]`);
      fillBlock = `

MAXIMIZE DIRECT HOURS — fill each underserved case toward 100% of its weekly direct target for the week of ${ctx.weekStart} by ADDING client-session (direct) ops inside the OPEN WINDOWS below, assigning one of the eligible techs listed for that window.
- Do NOT move or remove anything on the BCBA's own schedule (supervision / parent-training / case-planning / reassessment). You MAY ADD supervision when it helps a case meet its supervision %. You MAY ADD parent-training ONLY within the time span of an already-scheduled or newly-added session — never as a standalone window.
- Stay strictly inside each open window; only assign a tech listed as eligible for that window; never double-book a tech or client.
UNDERSERVED CASES (token: target, scheduled, gap): ${cases.join(' | ') || 'none'}
OPEN DIRECT WINDOWS (token date(day) start-end [eligible techs]): ${windows.join(' | ') || 'none'}
The 3 solutions should differ in how they trade techs/slots while maximizing total filled direct hours.`;

    } else if (wish.kind === 'fillSchedule') {
      // BCBA fills own calendar with supervision + PT within existing direct
      // sessions to bring cases toward ideal compliance range for the month.
      const ctx = buildComplianceFillContext(this.data, period, now);
      const tok = (m: Map<string, string>, id: string, name: string) => m.get(id) || m.get(name) || name;
      const aptTok = (id: string) => this.anonMap.appointments.get(id) || id;

      if (ctx.cases.length === 0) {
        fillBlock = `\nFILL MY SCHEDULE OUT — all cases are already at or above the ideal supervision range (${ctx.idealMinPct}%–${ctx.idealMaxPct}%) for ${ctx.periodLabel}. No supervision gaps to fill this month.`;
      } else {
        const caseLines = ctx.cases.map(c => {
          const clientTok = tok(this.anonMap.clients, c.clientId, c.clientName);
          return `${clientTok}: ${c.supPct}% supervision (${c.supHrs}h / ${c.directHrs}h direct), need +${c.gapToIdealHrs}h → ${ctx.idealMinPct}% ideal (cap ${c.idealMaxHrs}h = ${ctx.idealMaxPct}%)`;
        });
        const windowLines = ctx.directWindows.map(w => {
          const clientTok = tok(this.anonMap.clients, w.clientId, w.clientName);
          const techPart  = w.techName ? ` [${tok(this.anonMap.technicians, w.techId || '', w.techName)}]` : '';
          return `${clientTok} ${aptTok(w.appointmentId)} ${w.start.slice(0, 16).replace('T', ' ')}–${w.end.slice(11, 16)}${techPart}`;
        });

        fillBlock = `

FILL MY SCHEDULE OUT — add supervision and parent-training to bring each case toward the ideal supervision range (${ctx.idealMinPct}%–${ctx.idealMaxPct}% of direct hours) for ${ctx.periodLabel}.

FITNESS FUNCTION: Maximize cases reaching the ideal range. A 15-20% buffer above the ideal max (e.g. up to ~${(ctx.idealMaxPct * 1.18).toFixed(0)}%) is acceptable as a cancellation buffer — solutions that slightly exceed the ideal cap are preferred over leaving gaps. The BCBA will manually trim overages if needed.

RULES FOR THIS WISH:
- Only ADD new sessions. Do NOT move or remove any existing session.
- Supervision: place within an existing direct session's time window for the same client, naming that BT in the tech field — overlap is required for compliance credit.
- Parent Training: must fall within the time span of an existing direct session for the same client. Never add PT as a standalone window outside a direct session — it earns no credit and violates clinical rules.
- Aim for the ideal cap per case but do NOT refuse to add sessions just because the cap would be slightly exceeded. Soft cap — flag overages in reasoning.
- Never double-book the BCBA against existing supervision/PT/case-planning/reassessment in the schedule.
- Stay within BCBA availability.

UNDERSERVED CASES (token: sup%, gap to ideal, soft cap):
${caseLines.join('\n')}

FUTURE DIRECT SESSIONS — valid windows for supervision or PT (token: apt date start–end [BT]):
${windowLines.length ? windowLines.join('\n') : '(none remaining this month — gaps can only be addressed in future months)'}

The 3 solutions should differ in which sessions they prioritize and how they balance supervision vs parent-training.

NO-SOLUTION RULE: If no sessions can be placed (e.g. all windows are BCBA-blocked), return one solution with empty ops [] and detailed reasoning per case: which clients have windows, which are blocked, and WHY (BCBA conflict, outside availability, no future sessions).`;
      }
    }

    return `You are an ABA scheduler helping a BCBA reshape their schedule toward a goal. All people are opaque tokens — use exact tokens, never invent names.

NOW: ${now.toISOString()}
HORIZON: ${horizonEnd.toISOString().slice(0, 10)}

THE WISH:
${wish.kind === 'freeform'
  ? scrubText(summarizeWish(wish), this.data, this.anonMap)
  : summarizeWish(wish)}
${wish.kind !== 'freeform' && wish.note ? `Extra detail: ${scrubText(wish.note, this.data, this.anonMap)}` : ''}

HARD RULES:
1. Never touch any appointment whose start < NOW.
2. Items marked fixed cannot be moved. Respect technician and client availability windows.
3. Keep BCBA weekly billable ≥ required; supervision ${s.supervisionDirectHoursPercent}% of direct + ${s.supervisionRBTHoursPercent}% of RBT hours; parent training ≥ ${s.parentTraining.minimumHours}h per ${s.parentTraining.periodUnit}.
4. Prefer minimal change: move as few sessions as possible, keep recurring slots stable.
5. Never double-book a person. The BCBA is not listed in CLIENTS/TECHNICIANS but is the implicit actor on EVERY supervision/parent-training/case-planning/reassessment item — new or already in SCHEDULE IN HORIZON. Two such items (any client/tech combination) must never overlap in time. Diff every new add/move against (a) the other ops in the same solution and (b) every existing supervision/parent-training/case-planning/reassessment row in the schedule.
6. "add" ops must NOT include an "id" field — the app assigns IDs.
7. Each of the ≤3 solutions must be genuinely distinct.
${wish.shaveDown ? `8. SHAVE DOWN: where a case or RBT is OVER-served, you may shorten supervision toward the binding minimum — LARGEST of preferred-min ${s.supervisionPreferredMinPercent ?? 15}%, floor ${s.supervisionFloorPercent ?? 10}%, and BACB 5%. Never trim below that minimum.` : ''}

BCBA availability: ${clinicianAvail}
${fillBlock}
SCHEDULE IN HORIZON (compact JSON):
${JSON.stringify(inScope)}

CLIENTS: ${JSON.stringify(anon.clients)}
TECHNICIANS: ${JSON.stringify(anon.technicians)}
${anon.blackouts.length ? `BLACKOUT DAYS (each entry blocks only the named entity): ${JSON.stringify(anon.blackouts)}` : ''}
${anon.timeOff.length ? `BCBA TIME OFF: ${JSON.stringify(anon.timeOff)}` : ''}

VALIDATION (do mentally before answering): For every op verify — (a) start ≥ NOW; (b) no double-book of any tech or client; (b2) no two supervision/parent-training/case-planning/reassessment items (new ops AND existing schedule rows) overlap in time — the BCBA runs all of them and can only be in one at a time; (c) client/tech tokens exist in CLIENTS/TECHNICIANS; (d) apt tokens for move/remove exist in SCHEDULE; (e) proposed date+entity not in BLACKOUT DAYS; (f) BCBA not scheduled on TIME OFF; (g) skip any malformed token like "CLIENT_nIENT_m" — those are corrupted.

OUTPUT: Strict JSON only — no prose, no markdown. Exact schema (include only listed keys per op type):
{"solutions":[{"summary":"short title","reasoning":"1-2 sentences","ops":[
  {"op":"move","apt":"APT_n","start":"YYYY-MM-DDTHH:mm:ss","end":"YYYY-MM-DDTHH:mm:ss"},
  {"op":"remove","apt":"APT_n"},
  {"op":"add","title":"...","type":"supervision|parent-training|case-planning|client-session|reassessment|other","client":"CLIENT_n or null","tech":"TECH_n or null","start":"YYYY-MM-DDTHH:mm:ss","end":"YYYY-MM-DDTHH:mm:ss","recurring":false,"pattern":null},
  {"op":"blackout","entityType":"client|technician","entity":"CLIENT_n|TECH_n","date":"YYYY-MM-DD","reason":"..."}
]}]}
ISO times are local (no timezone suffix). If the wish can't be met compliantly, return one solution with empty ops and reasoning explaining why.`;
  }

  private buildPrompt(appointment: Appointment, conflicts: string[]): string {
    const anonAppt = anonymizeAppointment(appointment, this.anonMap);
    const endOfMonth = this.getEndOfMonth(appointment.startTime);
    const nowIso = new Date().toISOString();

    // Scrub conflicts: replace any names that snuck into messages.
    const scrubbedConflicts = conflicts.map(c => scrubText(c, this.data, this.anonMap));

    return `
You are a scheduling expert for an ABA (Applied Behavior Analysis) clinic. Resolve a scheduling conflict while maintaining regulatory compliance.

All people are referenced by opaque tokens (CLIENT_n, TECH_n, APT_n). Use these tokens in your response. Do NOT invent names.

CURRENT DATETIME: ${nowIso}

CONSTRAINTS:
- Compliance is fixed going forward only. NEVER change, complete, or reschedule an appointment that starts before the current datetime. Only adjust appointments at or after now.
- Never move a technician off another client's session to staff a different client, and never assume a technician is free during a block where they are already booked. If a requirement cannot be met within genuinely open availability, do NOT propose moving an existing session; instead state that it needs a manual entry.
- Supervision requirement: ${this.data.settings.supervisionDirectHoursPercent}% of direct hours + ${this.data.settings.supervisionRBTHoursPercent}% of RBT hours
- Parent training requirement: minimum ${this.data.settings.parentTraining.minimumHours} hours per ${this.data.settings.parentTraining.periodUnit} (target ${this.data.settings.parentTraining.targetMinHours}-${this.data.settings.parentTraining.targetMaxHours})
- Items marked "Fixed" cannot be moved
- Technician availability must be respected
- Client availability must be respected

CHANGED APPOINTMENT:
- ID: ${anonAppt.id}
- Technician: ${anonAppt.technician || 'none'}
- Client: ${anonAppt.client || 'none'}
- Time: ${anonAppt.startTime} to ${anonAppt.endTime}
- Type: ${anonAppt.type}
- Fixed: ${anonAppt.isFixed}
- Billable: ${anonAppt.isBillable}

CURRENT CONFLICTS:
${scrubbedConflicts.map(c => `- ${c}`).join('\n')}

DEADLINE: Solutions should ideally fit within the current week, but may extend to the end of the calendar month (${endOfMonth}) if necessary.

TASK: Generate 2-3 alternative scheduling solutions that resolve these conflicts. For each:
1. List which APT_<n> appointments to move and their new times (ISO 8601)
2. Explain why this solution works
3. Specify how many weeks it spans
4. Note if it's a single-week solution

Format each solution exactly as:
SOLUTION X:
Week span: <number> week(s)
Changes needed:
- APT_<n>: move from <ISO start> to <ISO end> -> <ISO start> to <ISO end>
Reasoning: <one paragraph>
Single-week: <yes|no>
    `;
  }

  private containsRawNames(prompt: string): boolean {
    // Whole-word match only — a plain substring check false-positives whenever
    // a client/tech name (ABA practices commonly use 2-letter initials, e.g.
    // "CL", "EC") happens to sit inside one of our own CLIENT_n/TECH_n tokens
    // ("CL"IENT_1, T"EC"H_1), aborting every call even though nothing leaked.
    const escape = (s: string) => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
    for (const c of this.data.clients) {
      if (c.name && c.name.length > 1 && new RegExp(`\\b${escape(c.name)}\\b`, 'i').test(prompt)) return true;
    }
    for (const t of this.data.technicians) {
      if (t.name && t.name.length > 1 && new RegExp(`\\b${escape(t.name)}\\b`, 'i').test(prompt)) return true;
    }
    return false;
  }

  private parseSolutions(text: string, changedAppointment: Appointment): ScheduleSolution[] {
    const solutions: ScheduleSolution[] = [];
    const solutionBlocks = text.split(/SOLUTION \d+:/);

    solutionBlocks.forEach((block, index) => {
      if (index === 0) return;

      const lines = block.trim().split('\n');
      const solution: ScheduleSolution = {
        id: uuidv4(),
        description: `Proposed Solution ${index}`,
        affectedWeeks: 1,
        weekSpan: { startDate: changedAppointment.startTime, endDate: changedAppointment.endTime },
        changes: [],
        reasoning: '',
        violatesConstraints: false,
      };

      let currentSection = '';
      lines.forEach(line => {
        const trimmed = line.trim();

        if (trimmed.startsWith('Week span:')) {
          const match = trimmed.match(/\d+/);
          solution.affectedWeeks = match ? parseInt(match[0]) : 1;
        } else if (trimmed.startsWith('Changes needed:')) {
          currentSection = 'changes';
        } else if (trimmed.startsWith('Reasoning:')) {
          solution.reasoning = trimmed.replace('Reasoning:', '').trim() || '';
          currentSection = 'reasoning';
        } else if (trimmed.startsWith('Single-week:')) {
          currentSection = '';
        } else if (currentSection === 'changes' && trimmed.startsWith('- ')) {
          // Try parse: "- APT_n: move from <s> to <e> -> <s> to <e>"
          const m = trimmed.match(/- (\S+): move from (\S+) to (\S+)\s*->?\s*(\S+) to (\S+)/);
          if (m && m[1] && m[2] && m[3] && m[4] && m[5]) {
            // De-anonymize APT_n back to real ID via reverse map
            const aptToken = m[1];
            const realId = this.anonMap.reverse.get(aptToken) || aptToken;
            solution.changes.push({
              appointmentId: realId,
              oldTime: { start: m[2], end: m[3] },
              newTime: { start: m[4], end: m[5] },
            });
          }
        } else if (currentSection === 'reasoning' && trimmed) {
          solution.reasoning = (solution.reasoning || '') + ' ' + trimmed;
        }
      });

      if (solution.changes.length > 0 && solution.reasoning) {
        solutions.push(solution);
      }
    });

    return solutions.slice(0, 3);
  }

  private getEndOfMonth(isoDate: string): string {
    const date = new Date(isoDate);
    const year = date.getFullYear();
    const month = date.getMonth();
    const lastDay = new Date(year, month + 1, 0);
    return lastDay.toISOString().split('T')[0] || '';
  }
}
